---
all:
  hosts:
    cygnus-5:
      ansible_host: cygnus-5.srv.0xef.de
      ansible_port: 2424
      ansible_become: yes
      ansible_user: hannes
      ansible_python_interpreter: /usr/bin/python3
