---
all:
  hosts:
    ###
    # 1024 SHA256:lMgf+CTtoq++YcOVAxjF1BlJ4MHYk4YVa434lDYW1R4 root@ubuntu (DSA)
    # 256 SHA256:c2ijU2bMDAKf7h9IA/bZfkUYtb7wNq+StZBpaLBK4z4 root@ubuntu (ECDSA)
    # 256 SHA256:G840URHik0GrtSRf4rakg+avRpyX3IwvmxJqNNhlqcA root@ubuntu (ED25519)
    # 3072 SHA256:IIXM1pnj8s7roazxOMYMaQgTegseu8+sXwD8+DY2DJg root@ubuntu (RSA)
    ###
    gw1:
      ansible_host: gw1.freifunk-potsdam.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 1
      gw2gw_use_ipv4: true
    ###
    # 1024 SHA256:bqxARwYfRba7dQGh3WGvouU1rmCbgHIVDbJsZJXGD+4 root@v22018085032971571 (DSA)
    # 256 SHA256:RFc10tG429Zk6j7/kZeRLZVh7VQaIHIBG1bRayCQRVs root@v22018085032971571 (ECDSA)
    # 256 SHA256:XUjHCy7NyatyHr08YrYtWmt1M70xt7i2sN3HZyhTY+I root@v22018085032971571 (ED25519)
    # 3072 SHA256:yzI0C8DSr7eUKxZ/hQB8fnAqeoYRbQBDSx5/DPB7GlY root@v22018085032971571 (RSA)
    ###
    gw2:
      ansible_host: gw2.freifunk-potsdam.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 2
    ###
    # 256 SHA256:Gd41zT3l5UYukNU8IrAzjXjFE9p8Wi5q6mu5HpnVfjE root@vmd53283 (ECDSA)
    # 256 SHA256:HJRSWcuxTqSgIchveeSNS7G7Crh3e2VF6gztEiMcYWY root@vmd53283 (ED25519)
    # 4096 SHA256:Zfz1Y9NrCuNk09JngTqMXTrXvhhKDRao3lT+yJg7u0g root@vmd53283 (RSA)
    ###
    gw3:
      ansible_host: gw3.freifunk-potsdam.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 3
      gw2gw_use_ipv4: true
    ###
    # 256 SHA256:FTkHftnOtfsfqZS2iRuI3D3AQGnSZGcIQtAM8ADDzDA root@monitoring (ECDSA)
    # 256 SHA256:QlSPnZwQU/u4FTBDqIKs9LS4jJITbeWGpja3CIlc7yo root@monitoring (ED25519)
    # 3072 SHA256:4caNB1/Js/ITnsobYJqYwNIf0yK0yl4bAZ7ilgvx3D4 root@monitoring (RSA)
    ###
    gw-monitoring:
      ansible_host: gw-monitoring.ffp.oci.0xef.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
  children:
    ffp_gw_he_net:
      hosts:
    ffp_gw:
      hosts:
        gw1:
        gw2:
        gw3:
