---
all:
  hosts:
    chapek-9:
      ansible_host: chapek-9.srv.0xef.de
      ansible_port: 2424
      ansible_become: yes
      ansible_python_interpreter: /usr/bin/python3
  children:
    ffp-gw:
      hosts:
        chapek-9:
