---
all:
  hosts:
    chapek-9:
      ansible_host: chapek-9.srv.0xef.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 1
  children:
    ffp-gw:
      hosts:
        chapek-9:
