---
all:
  hosts:
    ###
    # 1024 SHA256:Jp58kcnIHw0WVUCzaFYuZD0/gnpC6QSz4VY4a4kTT/k root@v220210335846145958 (DSA)
    # 256 SHA256:VxjYhGMB4Bx2Tbkc+4qmUrSpWo8KWvQnXK3MvSb8jPo root@v220210335846145958 (ECDSA)
    # 256 SHA256:As2kvkR5hf+h4mMZx7kJT0OMmH05m5vG4vZ28t/Bk74 root@v220210335846145958 (ED25519)
    # 3072 SHA256:gkHMQMD5I4aKMCyz6y7WL3E6cC9lDby1FO/tmFG2eCM root@v220210335846145958 (RSA)
    ###
    chapek-9:
      ansible_host: chapek-9.srv.0xef.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 1
    ###
    # 1024 SHA256:bqxARwYfRba7dQGh3WGvouU1rmCbgHIVDbJsZJXGD+4 root@v22018085032971571 (DSA)
    # 256 SHA256:RFc10tG429Zk6j7/kZeRLZVh7VQaIHIBG1bRayCQRVs root@v22018085032971571 (ECDSA)
    # 256 SHA256:XUjHCy7NyatyHr08YrYtWmt1M70xt7i2sN3HZyhTY+I root@v22018085032971571 (ED25519)
    # 3072 SHA256:yzI0C8DSr7eUKxZ/hQB8fnAqeoYRbQBDSx5/DPB7GlY root@v22018085032971571 (RSA)
    ###
    gw2:
      ansible_host: gw2.freifunk-potsdam.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 2
    ###
    # 256 SHA256:Gd41zT3l5UYukNU8IrAzjXjFE9p8Wi5q6mu5HpnVfjE root@vmd53283 (ECDSA)
    # 256 SHA256:HJRSWcuxTqSgIchveeSNS7G7Crh3e2VF6gztEiMcYWY root@vmd53283 (ED25519)
    # 4096 SHA256:Zfz1Y9NrCuNk09JngTqMXTrXvhhKDRao3lT+yJg7u0g root@vmd53283 (RSA)
    ###
    gw3:
      ansible_host: gw3.freifunk-potsdam.de
      ansible_port: 2424
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
      gw_number: 3
  children:
    ffp_gw_he_net:
      hosts:
        chapek-9:
    ffp_gw:
      hosts:
        gw2:
        gw3:
