---
collections:
  - name: devsec.hardening
    version: 8.2.0
  - name: prometheus.prometheus
    version: 0.11.3
roles:
  - src: hafu.systemd_timesyncd
  - src: Frzk.nftables
  - src: stuvusit.systemd-journald
  - name: weareinteractive.users
    version: 1.17.0
