---
administrative_users:
  - username: hannes
    password: "*"
    update_password: on_create
    groups:
      - systemd-journal
      - users
      - wheel
      - adm
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICZ14THlloupTncq14J51dVY25CvoJsLtxtNBrK1QIgp hannes@X570-A-JC17049246
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK/o0ynbYtLCSI0T1LpLOq7ar4atOwmhwH/SQEY0RvKX hannes@Swift1-SF114-32
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOwVnxyv4u1zi7foL8xvBqHK8shMqAdOr91ukt8q+TNv hfuchs@ThinkPad-T470p-PF0V4J38
  - username: seth0r
    password: "*"
    update_password: on_create
    groups:
      - systemd-journal
      - users
      - wheel
      - adm
    authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAHQUFccxGYu8KHwyJl2QNbc1qCC1HAUnOagOaoUgvSpVFuHRU4wTDzVi9HvJpr6cAqbdQdKuRkIe6LMlNZ83XJbAYlIUE2vI3mL24H1O9q4too2FN6owgNMe0jZVnbqKq7CuuUxGfwD4kpE64xikauOkh9OKFkvsss6ZitLghUGiVdgVJjjoXI5ZSdsMI8MR+lvKrXiorTyyi0pOx4E7zWDEYIHw3vaYkNgX8M4zCmfz7D3GFa1TVZjtnm5yrcrabtJHNun/WKDXkScS1bpCWa5Zb2mLLysxe0SFz6RhTTntuvPLcp1smWq+QahYX+UhhHMhgRSZ+CKLCbRNFa7R1 seth0r@Sia
