---

network_ipv6_enable: true

ssh_server_ports:
  - "2424"
ssh_listen_to:
  - "{{ ansible_default_ipv6.address|default('[::]') }}"
  - "{{ ansible_default_ipv4.address|default('0.0.0.0') }}"
ssh_host_key_files:
  - "/etc/ssh/ssh_host_ed25519_key"
  - "/etc/ssh/ssh_host_rsa_key"
ssh_allow_users: "hannes seth0r tommy"
ssh_allow_tcp_forwarding: "local"
ssh_authorized_keys_file: ".ssh/authorized_keys"
ssh_print_motd: true
ssh_print_pam_motd: true
ssh_print_last_log: true
sftp_enabled: true
ssh_client_hardening: false
