---
# tasks file for radvd

- name: Install radvd
  ansible.builtin.package:
    name: radvd

- name: Generate config
  ansible.builtin.template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart radvd

- name: Enable radvd service
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: radvd
    enabled: true
